### PR TITLE
Shrink size/styling of hero section on the index page

### PR DESCRIPTION
**Pull request by joelhans**
I noticed this morning that on my MacBook Air 13", the size of the hero section on the index page was a little ridiculous. And, given that we don't necessarily need to follow the styling of the Radicle app, I removed the Flexa font and made things generally smaller & neater.

**Before**
Screenshot 2023-02-16 at 10-37-20 RadicleDAO Documentation RadicleDAO Documentation

**After**
Screenshot 2023-02-16 at 10-37-06 RadicleDAO Documentation RadicleDAO Documentation

### CODE REVIEW

**Comment by shelbeeee** [comment]
@joelhans  I actually don't hate how big it is, but yeah maybe it's a bit too large. Could we try something in-between these two sizes? What do you think @abbey-titcomb ?

**Comment by joelhans** [comment]
Hey @shelbeeee! One more take on this that's in the middle between the big and small.

Screenshot 2023-03-06 at 11-09-55 RadicleDAO Documentation RadicleDAO Documentation

**Comment by shelbeeee** [comment]
This looks fine! Thanks Joel.

**Review by shelbeeee — APPROVED** [review]
Middle size font looks good!

**Pull request merged**
