### PR TITLE
"Degrees out" -> "hops out"

### PR DESCRIPTION
**Pull request by infinity0**
"Degree" is the number of neighbours of a particular node, it doesn't make sense to say "n degrees out"

### CODE REVIEW

**Comment by infinity0** [comment]
I didn't check the other documents or the code / UI so this change might need to be made in other places too.

**Review by abbey-titcomb — APPROVED** [review]
Cool, good feedback. LGTM — @xla, what do you think?

**Comment by xla** [comment]
Thanks for the contribution. I'm skeptical your change is an improvement as degrees refer to the nodes in a graph here, not the hops in network communication, like you have in gossip protocols. The tracking graph is the basis for data replication. Flagging this for future documentation where we talk about how packets flow through the network is meaningful,.

**Review by xla — CHANGES_REQUESTED** [review]
Might change the core message and mislead.

**Comment by infinity0** [comment]
Regardless of whether you think "hops" has too strong a connotation to network communication or not, the term "degree" is certainly incorrect here, it refers strictly to the number of direct neighbours of a node, and "n degrees out" is not a term in any discussions about either graph theory or network communication.

Sometimes "step" is used as an alternative to "hop" in the context of graph theory; both are generally well-understood including in terms of abstract graphs not network connections.

**Comment by cloudhead** [comment]
I think it comes from https://en.wikipedia.org/wiki/Six_degrees_of_separation

**Comment by infinity0** [comment]
That term was constructed a long time ago, before graph theory was applied widely to social and computer networks, and the word "degree" is used informally and loosely there like "6 levels of separation", and "separation" is the important part; i.e. it doesn't make sense to use the word "degree" by itself to refer to this concept.

**Comment by geigerzaehler** [comment]
I agree with @infinity0. “Hop” is the more appropriate technical term and “degree” is confusing. “Hop” is also the term [used by scuttlebutt](https://ssbc.github.io/scuttlebutt-protocol-guide/#follow-graph) which is very similar to our model.

**Pull request merged**
