### PR TITLE
Brandon/design update

### PR DESCRIPTION
**Pull request by brandonhaslegs**
A bunch of design changes to make it match the website more.

### CODE REVIEW

**Review by abbey-titcomb — APPROVED** [review]
Looks great to me! Much cleaner and more in line with the website. 

Only thing that bugs me is what "back to radicle.xyz" button - I think the size of it and the gray background throws me off. Maybe we could just remove it and have the logo link back to the homepage (which I think it already does?)

**Review by juliendonck — APPROVED** [review]
Amazing

**Comment by juliendonck** [comment]
> Looks great to me! Much cleaner and more in line with the website.
> 
> Only thing that bugs me is what "back to radicle.xyz" button - I think the size of it and the gray background throws me off. Maybe we could just remove it and have the logo link back to the homepage (which I think it already does?)

Doesn't bother me to be honest

**Comment by abbey-titcomb** [comment]
Oki! then let's merge diiiis

**Pull request merged**
