### PR TITLE
change USER to USERNAME in README

### PR DESCRIPTION
**Pull request by brandonhaslegs**
Just being more clear how to publish updates to the docs.

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
@rudolfs Why did I change so much on accident?

**Review by rudolfs — APPROVED** [review]

**Comment by rudolfs** [comment]
> Why did I change so much on accident?

I think your editor's markdown formatter went wild.

**Comment by brandonhaslegs** [comment]
is it bad or is it okay?

**Comment by rudolfs** [comment]
It's fine, don't worry about it.

**Pull request merged**
